// <auto-generated />
namespace PowerBI.ReportingServices.Security.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class useraccountv10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(useraccountv10));
        
        string IMigrationMetadata.Id
        {
            get { return "202108120738491_user-account-v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
